export enum LeadNotificationCode {
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  LEAD_UNASSIGNED = 'LEAD_UNASSIGNED',
  LEAD_DELETED = 'LEAD_DELETED',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
  LEAD_CHANGE_PRIMARY_AGENT = 'LEAD_CHANGE_PRIMARY_AGENT',
}
