export enum PropertyNotificationCode {
  PROPERTY_ASSIGNED = 'PROPERTY_ASSIGNED',
  PROPERTY_UNASSIGNED = 'PROPERTY_UNASSIGNED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  PROPERTY_SYSTEM_STATUS_CHANGED = 'PROPERTY_SYSTEM_STATUS_CHANGED',
  PROPERTY_BUSINESS_STATUS_CHANGED = 'PROPERTY_BUSINESS_STATUS_CHANGED',
  PROPERTY_LOW_RATING = 'PROPERTY_LOW_RATING',
}
